# Generated by Django 5.0.6 on 2024-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
                ('avlSeats', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
